// modulo2/prj4/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-dados',
  standalone: false,
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro(0, 0, '', '', []); 
  public autoresForm: string = ''; 
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras(); 
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n'); 
    this.servLivros.incluir(this.livro); 
    this.router.navigateByUrl('/lista'); 
  }
}
<main class="container mt-4">
  <h1 class="mb-4">Adicionar Novo Livro</h1>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="form-group">
      <label for="titulo">Título</label>
      <input type="text" id="titulo" class="form-control" [(ngModel)]="livro.titulo" name="titulo" required>
    </div>

    <div class="form-group">
      <label for="resumo">Resumo</label>
      <textarea id="resumo" class="form-control" [(ngModel)]="livro.resumo" name="resumo" required></textarea>
    </div>

    <div class="form-group">
      <label for="editora">Editora</label>
      <input type="text" id="editora" class="form-control" [(ngModel)]="livro.codEditora" name="editora" required>
    </div>

    <div class="form-group">
      <label for="autores">Autores</label>
      <textarea id="autores" class="form-control" [(ngModel)]="autoresForm" name="autores" required></textarea>
      <small class="form-text text-muted"></small>
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>
</main>

// modulo2/prj5/livros-servidor/clientes/livros-react/src/LivroDados.js
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";

const LivroDados = ({ onAddBook }) => {
  const [titulo, setTitulo] = useState("");
  const [resumo, setResumo] = useState("");
  const [autores, setAutores] = useState("");
  const [codEditora, setCodEditora] = useState(0);
  const navigate = useNavigate();

  const editoras = [
    { codEditora: 1, nome: "Alta Books" },
    { codEditora: 2, nome: "Pearson" },
    { codEditora: 3, nome: "Addison Wesley" }
  ];

  const opcoes = editoras.map(ed => ({
    value: ed.codEditora,
    text: ed.nome
  }));

  const tratarCombo = (event) => {
    setCodEditora(Number(event.target.value));
  };

  const incluir = (event) => {
    event.preventDefault();

    const autoresArray = autores.split("\n");
    const novoLivro = {
      codigo: "", 
      titulo,
      resumo,
      autores: autoresArray,
      codEditora
    };

    onAddBook(novoLivro).then(() => {
      navigate("/"); 
    });
  };

  return (
    <div className="container mt-4">
      <h2>Adicionar Novo Livro</h2>
      <form onSubmit={incluir} className="form">
        <div className="mb-3">
          <label htmlFor="titulo" className="form-label">Título</label>
          <input
            type="text"
            id="titulo"
            value={titulo}
            onChange={(e) => setTitulo(e.target.value)}
            className="form-control"
            required
          />
        </div>
        <div className="mb-3">
          <label htmlFor="resumo" className="form-label">Resumo</label>
          <textarea
            id="resumo"
            value={resumo}
            onChange={(e) => setResumo(e.target.value)}
            className="form-control"
            rows={3}
            required
          ></textarea>
        </div>
        <div className="mb-3">
          <label htmlFor="autores" className="form-label">Autores (separados por linha)</label>
          <textarea
            id="autores"
            value={autores}
            onChange={(e) => setAutores(e.target.value)}
            className="form-control"
            rows={3}
            required
          ></textarea>
        </div>
        <div className="mb-3">
          <label htmlFor="editora" className="form-label">Editora</label>
          <select
            id="editora"
            value={codEditora}
            onChange={tratarCombo}
            className="form-control"
            required
          >
            {opcoes.map((opcao) => (
              <option key={opcao.value} value={opcao.value}>
                {opcao.text}
              </option>
            ))}
          </select>
        </div>
        <button type="submit" className="btn btn-primary">Adicionar Livro</button>
      </form>
    </div>
  );
};

export default LivroDados;
