// modulo2/prj5/livros-servidor/clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { Livro } from '../livro';

@Component({
  selector: 'app-livro-lista',
  standalone: false,
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}

  ngOnInit(): void {
   
    this.servLivros.obterLivros().then(livros => {
      this.livros = livros;
      console.log(this.livros);
    });
    this.editoras = this.servEditora.getEditoras();
  }

 
  excluir = (codigo: string): void => {
    this.servLivros.excluir(codigo).then(() => {
  
      this.servLivros.obterLivros().then(livros => {
        this.livros = livros;
      });
    });
  }

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}
<main class="container mt-4">
  <h1 class="mb-4">Lista de Livros</h1>
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>Título</th>
        <th>Editora</th>
        <th>Autores</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>{{ livro.titulo }}</td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <ul class="list-unstyled">
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
        <td>
          <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
        </td>
      </tr>
    </tbody>
  </table>
</main>

// modulo2/prj3/livros-react/src/LivroLista.js
import React from "react";

const LivroLista: React.FC<{ livros: any[], onExcluir: (codigo: number) => void, getNomeEditora: (codEditora: number) => string }> = ({ livros, onExcluir, getNomeEditora }) => {
  return (
    <div>
      <h2>Lista de Livros</h2>
      <table className="table">
        <thead>
          <tr>
            <th>Título</th>
            <th>Resumo</th>
            <th>Editora</th>
            <th>Autores</th>
            <th>Ações</th> {}
          </tr>
        </thead>
        <tbody>
          {livros.map((livro) => (
            <tr key={livro.codigo}>
              <td>{livro.titulo}</td>
              <td>{livro.resumo}</td>
              <td>{getNomeEditora(livro.codEditora)}</td> {}
              <td>{livro.autores.join(", ")}</td>
              <td>
                <button
                  className="btn btn-danger"
                  onClick={() => onExcluir(livro.codigo)} 
                >
                  Excluir
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default LivroLista;
